# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='static/files', verbose_name='Imagen'),
        ),
    ]
