# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-27 03:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0005_auto_20160626_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='fecha_entrega',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='orden',
            name='fecha_expedicion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
