# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-14 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0008_auto_20160714_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumoproducto',
            name='costototal',
            field=models.FloatField(default=0),
        ),
    ]
