# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-15 04:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0010_productoorden_costo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoorden',
            name='costo',
        ),
    ]
