# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-16 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0013_auto_20160715_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='estatus',
            field=models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Confirmada'), (3, 'Proceso'), (4, 'Conflicto'), (5, 'Cancelada'), (6, 'Entregada')], default=1),
        ),
    ]
