# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-17 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0014_auto_20161116_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='nota',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True),
        ),
    ]
