# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-30 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0015_auto_20161116_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='fecha_entrega_almacen',
            field=models.DateField(blank=True, null=True),
        ),
    ]
