# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-01 00:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produccion', '0016_orden_fecha_entrega_almacen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha_expedicion', models.DateField(default=django.utils.timezone.now)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('estatus', models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Confirmada'), (3, 'Proceso'), (4, 'Conflicto'), (5, 'Cancelada'), (6, 'Entregada')], default=1)),
                ('costo', models.FloatField(default=0)),
                ('entrega', models.IntegerField(choices=[(1, 'Bodega'), (2, 'Flete')], default=1)),
                ('fecha_entrega_almacen', models.DateField(blank=True, null=True)),
                ('direccionentrega', models.CharField(blank=True, max_length=255, null=True)),
                ('costoflete', models.FloatField(default=0)),
                ('nota', models.TextField(blank=True, max_length=1000, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.Cliente')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
