# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-01 01:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produccion', '0018_auto_20161130_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentariosCotizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('comentario', models.CharField(blank=True, max_length=500, null=True)),
                ('estatus', models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Confirmada'), (3, 'Proceso'), (4, 'Conflicto'), (5, 'Cancelada')], default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='estatus',
            field=models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Confirmada'), (3, 'Proceso'), (4, 'Conflicto'), (5, 'Cancelada'), (6, 'Entregada')], default=1),
        ),
        migrations.AddField(
            model_name='comentarioscotizacion',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.Cotizacion'),
        ),
        migrations.AddField(
            model_name='comentarioscotizacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
