# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-01 01:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produccion', '0019_auto_20161130_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInsumoProductoCotizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('estatus', models.CharField(max_length=140)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.InsumoProducto')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoCotizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField()),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('comentario', models.CharField(blank=True, max_length=1000, null=True)),
                ('unidad', models.IntegerField(choices=[(1, 'Pieza'), (2, 'Metro'), (3, 'Kilo'), (4, 'Litro')], default=1)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.Cotizacion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.Producto')),
            ],
        ),
        migrations.AddField(
            model_name='checkinsumoproductocotizacion',
            name='productorden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.ProductoCotizacion'),
        ),
        migrations.AddField(
            model_name='checkinsumoproductocotizacion',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
