# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-02 01:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0020_auto_20161130_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='costoflete',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='direccionentrega',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='entrega',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='fecha_entrega',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='fecha_entrega_almacen',
        ),
    ]
