# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-08 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0021_auto_20161201_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='costo_venta',
            field=models.FloatField(default=0),
        ),
    ]
