# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-09 03:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0024_ordenalmacen'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoAlmacenMod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=255)),
                ('costo', models.FloatField(default=0)),
                ('precio_venta', models.FloatField(default=0)),
                ('file', models.FileField(blank=True, null=True, upload_to='static/files', verbose_name='Imagen')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produccion.Categoria')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoOrdenAlmacen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField()),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('comentario', models.CharField(blank=True, max_length=1000, null=True)),
                ('unidad', models.IntegerField(choices=[(1, 'Pieza'), (2, 'Metro'), (3, 'Kilo'), (4, 'Litro')], default=1)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.Orden')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.ProductoAlmacenMod')),
            ],
        ),
    ]
