# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-09 03:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produccion', '0025_productoalmacenmod_productoordenalmacen'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentariosOrdenAlmacen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('comentario', models.CharField(blank=True, max_length=500, null=True)),
                ('estatus', models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Confirmada'), (3, 'Proceso'), (4, 'Conflicto'), (5, 'Cancelada')], default=1)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.OrdenAlmacen')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='productoordenalmacen',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.OrdenAlmacen'),
        ),
    ]
