# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-09 03:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0026_auto_20170108_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoalmacenmod',
            name='orden',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='produccion.OrdenAlmacen'),
            preserve_default=False,
        ),
    ]
