# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-09 03:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0014_auto_20160920_0106'),
        ('produccion', '0027_productoalmacenmod_orden'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsumoProductoMod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField()),
                ('costototal', models.FloatField(default=0)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.Insumo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.ProductoAlmacenMod')),
            ],
        ),
    ]
