# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-09 04:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0029_checkinsumoproductoalmacen'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostoEspecialAlmacen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=255)),
                ('costo', models.FloatField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.ProductoAlmacenMod')),
            ],
        ),
    ]
