# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-20 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0031_auto_20170213_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='costo',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='comentarioscotizacion',
            name='estatus',
            field=models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Completada'), (3, 'Cancelada')], default=1),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='estatus',
            field=models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Completada'), (3, 'Cancelada')], default=1),
        ),
    ]
