# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-20 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0014_auto_20160920_0106'),
        ('produccion', '0032_auto_20170220_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostoEspecialCotizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=255)),
                ('costo', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='InsumoCotizacionMod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField()),
                ('costototal', models.FloatField(default=0)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.Insumo')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoCotizacionMod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=255)),
                ('costo', models.FloatField(default=0)),
                ('precio_venta', models.FloatField(default=0)),
                ('file', models.FileField(blank=True, null=True, upload_to='static/files', verbose_name='Imagen')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produccion.Categoria')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.Cotizacion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.Producto')),
            ],
        ),
        migrations.RemoveField(
            model_name='checkinsumoproductocotizacion',
            name='insumo',
        ),
        migrations.RemoveField(
            model_name='checkinsumoproductocotizacion',
            name='productorden',
        ),
        migrations.RemoveField(
            model_name='checkinsumoproductocotizacion',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='productocotizacion',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.ProductoCotizacionMod'),
        ),
        migrations.DeleteModel(
            name='CheckInsumoProductoCotizacion',
        ),
        migrations.AddField(
            model_name='insumocotizacionmod',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.ProductoCotizacionMod'),
        ),
        migrations.AddField(
            model_name='costoespecialcotizacion',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.ProductoCotizacionMod'),
        ),
    ]
