# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-21 16:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0035_auto_20170221_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoorden',
            name='producto',
        ),
    ]
