# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-18 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0036_remove_productoorden_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='printdesc',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='descripcion',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
