# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-18 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0037_auto_20170318_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='terminada',
            field=models.BooleanField(default=False),
        ),
    ]
