# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-19 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0038_cotizacion_terminada'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='ordenventa',
            field=models.BooleanField(default=False),
        ),
    ]
