# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-22 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0039_cotizacion_ordenventa'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='vconfirm',
            field=models.BooleanField(default=False),
        ),
    ]
