# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 04:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0003_auto_20160523_0157'),
    ]

    operations = [
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='insumo',
            name='file',
            field=models.FileField(upload_to='static/files', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='stock',
            name='insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.Insumo'),
        ),
    ]
