# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 07:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0008_auto_20160530_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='cantidad',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.Insumo'),
        ),
    ]
