# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0009_auto_20160530_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salida',
            name='cantidad',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='salida',
            name='insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.Insumo'),
        ),
    ]
