# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-14 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0010_auto_20160601_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='costostock',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='insumo',
            name='costounitario',
            field=models.FloatField(default=0),
        ),
    ]
