# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-19 04:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0012_auto_20160918_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenconcepto',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='ordenconcepto',
            name='unidad',
        ),
        migrations.AddField(
            model_name='ordenconcepto',
            name='insumo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='almacen.Insumo'),
            preserve_default=False,
        ),
    ]
