# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-20 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0013_auto_20160918_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenconcepto',
            name='recibido',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='estatus',
            field=models.IntegerField(choices=[(1, 'Creada'), (2, 'Pendiente'), (3, 'Ingreso'), (4, 'Cancelada')], default=1),
        ),
    ]
