# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-22 17:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produccion', '0036_remove_productoorden_producto'),
        ('almacen', '0015_auto_20170222_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenMateriales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('total', models.FloatField(default=0)),
                ('estatus', models.IntegerField(choices=[(1, 'Creada'), (2, 'Pendiente'), (3, 'Ingreso'), (4, 'Cancelada')], default=1)),
                ('iva', models.BooleanField(default=False)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.OrdenAlmacen')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenMaterialesConcepto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField()),
                ('total', models.FloatField(default=0)),
                ('pedir', models.BooleanField(default=False)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.Insumo')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.OrdenMateriales')),
            ],
        ),
    ]
